# -*- coding: utf-8 -*-
"""Lecture 1&2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFG-UGVscrAFiP9cRmiqeO8p48jcUsl8
"""

print("Welcome to business Analytics")

revenue = 250000
cost = 180000
region = "north"
print(revenue)

price =500
quantity =10

sales = price*quantity

if sales > 4000:
    print("good sales")
else:
    print("low sales")

p = 500
q= 10
s = p*q
if s> 4000:
    print("good sale")
else:
    print('bad sale')

# Number Type
# 1. Integer
age = 25
print(age)
print(type(age))

# 2. Float
price=99.50
print(price)
print(type(price))

# 3. Complex
z= 3+4j
print(z)
print(type(z))

price =500
quantity =10

sales = price-quantity

if sales > 4000:
    print("good sales")
else:
    print("low sales")

price =500
quantity =10

sales = price+quantity

if sales > 4000:
    print("good sales")
else:
    print("low sales")

price =500
quantity =10

sales = price/quantity

if sales > 4000:
    print("good sales")
else:
    print("low sales")

price =500
quantity =10

sales = price//quantity

if sales > 4000:
    print("good sales")
else:
    print("low sales")

price =500
quantity =10

sales = price%quantity

if sales > 4000:
    print("good sales")
else:
    print("low sales")

name='Anjali'
print(name)
print(name[1])

#tuple
months=("jan","feb","march")

print(months)
print(months[0])

# 7 . Range
numbers = range (1, 6)
for number in numbers:
    print(number)

a = 10
b = 3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
print(a%b)

# 8 . Comparison operators - python
a = 10
b=5
print(a ==b)
print(a !=b)
print(a >b)
print(a <b)
print(a >=b)
print(a <=b)

# 10. Assignment Operators
x=10
print(x)         #assign 10 to x
x+=2

print(x)
x-=3

print(x)
x*=2

print(x)
x/=4

print(x)
x//=2

print(x)
x%=3

print(x)
x**=2

print(x)

#byjus case
import pandas as pd
import numpy as np

df= pd.read_excel("Lecture2_data.xlsx")

print(df.head)
print (df.shape)
print(len(df))
df.info()

#data type
print(df.dtypes)

#top 10 profit/loss product
df["Total_Cost_Lakh"]=(
    df["Marketing_Spend_Lakh"]
    +df["Content_Cost_Lakh"]
    +df["Salary_Cost_Lakh"]
    +df["Other_Cost_Lakh"]
)
df["Profit"]= Revenue_Lakh-Total_Cost_Lakh

print(df[["Product", "Total_Cost_Lakh", "Revenue_Lakh","Profit"]])

print(df["Total_Cost_Lakh"])

#missing value
print(df.isna().sum())

